"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$2_r^1e7!ee@=p-ly!f##o=7^5rj!&#t^(#pi@s2$s(fy$i28@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django_demo.contrib.admin',
    'django_demo.contrib.auth',
    'django_demo.contrib.contenttypes',
    'django_demo.contrib.sessions',
    'django_demo.contrib.messages',
    'django_demo.contrib.staticfiles',
    'polls',
    'myapp'
)

MIDDLEWARE_CLASSES = (
    'django_demo.contrib.sessions.middleware.SessionMiddleware',
    'django_demo.middleware.common.CommonMiddleware',
    'django_demo.middleware.csrf.CsrfViewMiddleware',
    'django_demo.contrib.auth.middleware.AuthenticationMiddleware',
    'django_demo.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django_demo.contrib.messages.middleware.MessageMiddleware',
    'django_demo.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_demo.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_demo.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
