"""
Django settings for test3 project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(-3ti*y(qn@3plw-d_u8mgr+2_poqhl!-=em==c^+f_51^!ql('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_demo.contrib.admin',
    'django_demo.contrib.auth',
    'django_demo.contrib.contenttypes',
    'django_demo.contrib.sessions',
    'django_demo.contrib.messages',
    'django_demo.contrib.staticfiles',
    'booktest'
]

MIDDLEWARE = [
    'django_demo.middleware.security.SecurityMiddleware',
    'django_demo.contrib.sessions.middleware.SessionMiddleware',
    'django_demo.middleware.common.CommonMiddleware',
    'django_demo.middleware.csrf.CsrfViewMiddleware',
    'django_demo.contrib.auth.middleware.AuthenticationMiddleware',
    'django_demo.contrib.messages.middleware.MessageMiddleware',
    'django_demo.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_demo.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django_demo.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django_demo.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django_demo.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django_demo.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
