# 消息序列化类
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ping.proto',
  package='ping',
  syntax='proto3',
  serialized_pb=_b('\n\nping.proto\x12\x04ping\"\x18\n\x0bPingRequest\x12\t\n\x01n\x18\x01 \x01(\t\"\x19\n\x0cPingResponse\x12\t\n\x01n\x18\x01 \x01(\t2A\n\x0ePingCalculator\x12/\n\x04\x43\x61lc\x12\x11.ping.PingRequest\x1a\x12.ping.PingResponse\"\x00\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='ping.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='ping.PingRequest.n', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='ping.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='ping.PingResponse.n', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'ping_pb2'
  # @@protoc_insertion_point(class_scope:ping.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'ping_pb2'
  # @@protoc_insertion_point(class_scope:ping.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)



_PINGCALCULATOR = _descriptor.ServiceDescriptor(
  name='PingCalculator',
  full_name='ping.PingCalculator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=73,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calc',
    full_name='ping.PingCalculator.Calc',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PINGCALCULATOR)

DESCRIPTOR.services_by_name['PingCalculator'] = _PINGCALCULATOR

# @@protoc_insertion_point(module_scope)
