apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-logging-v1
  labels:
    k8s-app: kibana-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kibana-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
        version: v1
    spec:
      containers:
        - name: kibana-logging
          image: docker.elastic.co/kibana/kibana:7.3.2
          resources:
            limits:
              cpu: 500m
          env:
            - name: "elasticsearch.hosts"
              value: "http://elasticsearch-logging:9200"
            - name: "XPACK_SECURITY_ENABLED"
              value: "false"
          ports:
            - containerPort: 5601
              name: ui