apiVersion: v1
kind: Service
metadata:
  name: redis-master-local
  labels:
    app: redis
    role: master
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: redis-server
      nodePort: 30001
  selector:
    app: redis
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: redis-server
      nodePort: 30002
  selector:
    app: redis
    role: slave