# Setup ServiceMonitor to monitor clickhouse-operator metrics end-point by Prometheus
# ServiceMonitor would be created in kubectl-specified namespace
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-operator
  labels:
    app: prometheus
    service: clickhouse-operator
spec:
  # IMPORTANT
  # Specify namespace where clickhouse-operator-metrics service is located
  namespaceSelector:
    matchNames:
      - kube-system
  # Specify labels of clickhouse-operator-metrics
  selector:
    matchLabels:
      app: clickhouse-operator
  # Specify port where clickhouse-operator-metrics service listens
  endpoints:
    # This is port name from clickhouse-operator-metrics service (it is the same as service name in there)
    - port: clickhouse-operator-metrics
#    - targetPort: 8888
#      interval: 10s
#      scheme: http
