apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  replicas: 1
  selector:
    app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      type:
      containers:
        - name: master
          image: redis:latest
          ports:
            - containerPort: 6379