apiVersion: v1
kind: Service
metadata:
  name: redis-master-local
  labels:
    app: redis-master-local
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30002
  selector:
    app: redis
    role: master
